# Separates each Terraform action into separate steps in the pipeline.
# Authorization token is exported in the first steps after logging into Azure using Az CLI.
# Script then exports information into environment variables.

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - name: workingDirectory
    value: azcli

stages:
- stage: validate
  displayName: 'Validate'
  jobs:
    - job: Validate
      steps:
      - checkout: self
        clean: true
      
      - task: AzureCLI@2
        name: set_variables
        displayName: set terraform credentials
        inputs:
          azureSubscription: '<service connection>'
          addSpnToEnvironment: true
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: |
            Write-Host "##vso[task.setvariable variable=ARM_USE_OIDC]true"
            Write-Host "##vso[task.setvariable variable=ARM_USE_AZUREAD]true"
            Write-Host "##vso[task.setvariable variable=ARM_OIDC_TOKEN]$env:idToken"
            Write-Host "##vso[task.setvariable variable=ARM_CLIENT_ID]$env:servicePrincipalId"
            Write-Host "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$(az account show --query id -o tsv)"
            Write-Host "##vso[task.setvariable variable=ARM_TENANT_ID]$env:tenantId"
      
      - pwsh: |
          terraform init -backend-config backend.hcl
        displayName: 'terraform init'
        workingDirectory: $(workingDirectory)

      - pwsh: |
          terraform validate
        displayName: 'terraform validate'
        workingDirectory: $(workingDirectory)

      - pwsh: |
          terraform plan
        displayName: 'terraform plan'
        workingDirectory: $(workingDirectory)

- stage: deploy
  displayName: 'Deploy'
  dependsOn:
  - validate
  jobs:
    - job: 'Deploy'
      steps:
      - checkout: self
        clean: true
      
      - task: AzureCLI@2
        name: set_variables
        displayName: set terraform credentials
        inputs:
          azureSubscription: '<service connection>'
          addSpnToEnvironment: true
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: |
            Write-Host "##vso[task.setvariable variable=ARM_USE_OIDC]true"
            Write-Host "##vso[task.setvariable variable=ARM_USE_AZUREAD]true"
            Write-Host "##vso[task.setvariable variable=ARM_OIDC_TOKEN]$env:idToken"
            Write-Host "##vso[task.setvariable variable=ARM_CLIENT_ID]$env:servicePrincipalId"
            Write-Host "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$(az account show --query id -o tsv)"
            Write-Host "##vso[task.setvariable variable=ARM_TENANT_ID]$env:tenantId"

      - pwsh: |
          terraform init -backend-config backend.hcl
        displayName: 'terraform init'
        workingDirectory: $(workingDirectory)

      - pwsh: |
          terraform apply --auto-approve
        displayName: 'terraform apply'
        workingDirectory: $(workingDirectory)